version: "3"

services:
  oracle-db:
    container_name: oracle-db
    build:
      context: ./oracle-xe
      dockerfile: Dockerfile.xe
    networks:
      - oracle_network
    env_file:
      - ./stack.env
    volumes:
      - ./db-data:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 5500:5500
    restart: unless-stopped
  apex-tomcat:
    container_name: apex-tomcat
    image: tomcat:latest
    networks:
      - oracle_network
    env_file:
      - ./stack.env
    volumes:
      - ./tomcat-data:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - oracle-db
networks:
  oracle_network: