services: 
  oracle-xe:
    privileged: true
    container_name: db
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    env_file: 
      - "./environment/oracle.env"
    volumes: 
      - "oracle-data:/opt/oracle/oradata"
    networks: 
      oracle_net:
        aliases:
          - xe
          - db
  ords:
    container_name: ords
    image: container-registry.oracle.com/database/ords-developer:latest
    ports:
      - "8181:8181"
    env_file: 
      - "./environment/oracle.env"
    volumes: 
      - "./environment/:/opt/oracle/variables/"
      - "ords_config:/etc/ords/config/"
    networks: 
      oracle_net:
        aliases:
          - ords
    depends_on: 
      - oracle-xe
networks: 
  oracle_net:
    name: oracle_net
volumes:
  oracle-data:
    driver: local
  ords_config:
    driver: local


